name: Farm Manager CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fkaaziebu
          password: Microsoft@2021

      - name: Build Docker image (linux/arm64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag fkaaziebu/farm-manager-mcp-server:latest \
            --push \
            .
